### ISSUE TITLE
Check and eventually fix ergoCub lower leg frames orientation

### ISSUE THREAD

**Issue by paolo-viceconte** [icub-tech-iit/ergocub-software#74] opened 2023-03-14 11:41 UTC
By visualizing the ergoCub link frames in Gazebo I noticed that the ergoCub link frames are all oriented as iCubV3 but the lower leg ones, which are instead rotated of 180 degs around the x axis (z pointing downwards rather than upwards):

![lower_leg_frames](https://user-images.githubusercontent.com/41757826/224050001-6fde20c0-701f-4692-bec0-55ed24025a68.png)

If this is not intended for specific purposes, maybe it is worth to have them oriented as all the other links in the chain.

cc @traversaro @S-Dafarra @GiulioRomualdi

**Comment by Nicogene** [comment] 2023-09-20 13:56
Hi @Mick3Lozzo,

I noticed that you committed the fixes after pulling `cad-mechanics`, next time please drop a comment here in order I receive the notification.

Your changes align the knee frames but here is the resulting urdf

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/4320c4df-cdf5-43ee-b61f-fdfd20ec8b93)

Also checking the diff seems that the whole part has been roll-ed up for having the z up

```diff
-    <origin xyz="0.01060000963260986 0.007899987075259199 -0.17970000000000103" rpy="-3.1415926535897274 -8.69101748565412e-14 -1.2193157698906137e-6"/>
-    <axis xyz="-2.0458175022504648e-17 1 2.5382740632965355e-17"/>
+    <origin xyz="0.01060000963260985 0.007899987075259289 -0.17970000000000058" rpy="6.892643261935339e-14 -6.650159361880639e-14 -1.2193157700904425e-6"/>^M
+    <axis xyz="1.7937066152151813e-16 -1 3.2454535731621664e-15"/>
```

Probably something went wrong in the regeneration of the simp rep? 

It has to be investigated

cc @pattacini @mfussi66

**Comment by pattacini** [comment] 2023-09-29 08:42
@Mick3Lozzo 

Can you please resume here the current status?

**Comment by Mick3Lozzo** [comment] 2023-09-29 09:19
@pattacini I corrected and updated both the CAD and shrink-wrapped models (for the `ergoCub_1-1 `sim model).
The shrink-wrapped model does not use the CSYSes as a constraint, so the legs' placement is correct.

![image](https://github.com/icub-tech-iit/ergocub-software/assets/15085666/76c5f0d4-f152-4242-8082-d1b278507014)

[This problem](https://github.com/icub-tech-iit/ergocub-software/issues/74#issuecomment-1727786937) still has to be investigated.

**Comment by Nicogene** [comment] 2023-10-04 09:10
Today I managed to understand what was the cause of this problem.
Basically, I forgot to update also the meshes after the change of orientation of the csys. Now it looks fine:

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/51167fc5-16ca-40f5-ba55-2328b68c9f33)


PR:
- https://github.com/icub-tech-iit/ergocub-software/pull/181


> [!WARNING]  
> In order to fix this issue it is needed to change the simulation model and reassemble it. Since ergoCubV1 cad has not been changed/fixed for a while, this fix will be carried only on ergoCubV1_1 models.

cc @Mick3Lozzo @pattacini

**Closed** 2023-10-04 09:19 UTC
Labels: domain-mechanics, domain-software, prj-ergocub, team-fix
