### ISSUE TITLE
Wrong lidar mounting on ergocubSN000

### ISSUE THREAD

**Issue by SimoneMic** [icub-tech-iit/ergocub-software#131] opened 2023-06-14 10:57 UTC
Hello,

Today we've tested the lidar on the robot and we have seen a mismatch between the mounting of the lidar with the URDF of the robot.
In few words: the lidar should be rotated by 90 degrees clockwise.

Here's a screenshot of the lidar on Rviz, the readings circled in blue are the ones crane and the support of the robot that should be behind. Here they are on the right of the robot (the red axis in Rviz is the x-axis that points forward)

![Capture3](https://github.com/icub-tech-iit/ergocub-software/assets/86918431/eba9e12b-7c26-4e35-a452-8bc480633583)

![Capture](https://github.com/icub-tech-iit/ergocub-software/assets/86918431/95896cda-1ed3-4053-8f62-0ac9006ae151)

Here we tried to put a box behind the robot and is still displayed to the side
![Capture2](https://github.com/icub-tech-iit/ergocub-software/assets/86918431/cf481bd7-9b96-4c83-981f-bd2d5ee2386a)

Do we change the URDF of the robot or fix the mounting of the lidar?
The easiest way is to adapt the URDF, but then it should be consistent through all the other versions of ergocub and also the model on gazebo

**Comment by pattacini** [comment] 2023-06-14 11:11
Thanks for reporting 👍🏻 

>Do we change the URDF of the robot or fix the mounting of the lidar?
The easiest way is to adapt the URDF, but then it should be consistent through all the other versions of ergocub and also the model on gazebo

We need to check which is the intended mounting and then adapt accordingly.

**Comment by pattacini** [comment] 2023-06-15 06:57
From a first inspection, it came out that the LIDAR is mounted correctly as per the CAD.
The problem should be then a missing/wrong CSYS that impacted the URDF.

Stay tuned.

**Comment by Nicogene** [comment] 2023-06-15 12:09
This issue is confirmed by the fact that right now this is the frame exported

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/c31ff899-87c9-4b83-8403-b41ecc39b510)


But the datasheet says that the x is ahead

![immagine](https://github.com/icub-tech-iit/ergocub-software/assets/19152494/abb889f9-1d3c-4707-91b3-aeed0e7ea645)

**Comment by randaz81** [comment] 2023-06-15 16:00
No, the lidar is right-handed.
The x is pointing forward, y on the left, z is pointing upward. Scans dara are ordered CCW.
As mentioned by @SimoneMic just a 90 deg rotation is fine to fix the issue.

**Comment by randaz81** [comment] 2023-06-15 16:03
What is shown in the datasheet picture mentioned above should be considered wrong and is not consistent with our yarp/ros data representation.

**Comment by pattacini** [comment] 2023-06-16 06:50
Hi @randaz81 

It's true that a left-handed triplet is kind of unusual/weird but could you elaborate more on the following?

> What is shown in the datasheet picture mentioned above should be considered wrong and is not consistent with our yarp/ros data representation.

To which extent should the datasheet be considered misleading?

**Comment by randaz81** [comment] 2023-06-16 07:29
Because it states: "The rotation angle increases as rotating clockwise".

However, we are representing the scan data ordered _counterclockwise_.
In fact, giving an X pointing to the front of the robot, and Y pointing to the left, then Z is pointing upwards (right-handed).
And Z pointing upwards defines a _counterclockwise_ rotation on a right-handed reference system (which is ok, while a clockwise rotation would be left-handed).

Extras about ROS standards:
https://www.ros.org/reps/rep-0103.html
https://www.ros.org/reps/rep-0105.html

**Comment by pattacini** [comment] 2023-06-16 07:51
>Because it states: "The rotation angle increases as rotating clockwise".

This is expected for a left-handed triplet, I think.

Theoretically, we ought to insert in the CAD the information relative to the physical device to then deal with it at a higher level.

Nonetheless, there are a bunch of things to consider as well:
- The flexibility of the CAD to deal with left-handed CSYS.
- The possibility to have left-handed within a URDF (probably there ain't any).

cc @fiorisi @Nicogene @maggia80

**Comment by randaz81** [comment] 2023-06-16 09:52
It's possible that the datasheet represents how the device internally works, i.e. the direction of rotation of the motor (for the S2 device it is hidden inside the case so it cannot be seen from outside). However, the SDK provides an array of tuples [angle, distance] in random order (for example, the angle could be: 3, 4, 7, 5, 2..] and is up to the user to process it. However, I don't think that is necessary to know these internal details exactly: given the fact the device has axial symmetry, the x axis, which defines the 0 angle, is defined merely by the software, and it can be placed (in our device driver code) as the user prefers. In our case, we are publishing data following the ROS convention, and what the datasheet says can be completely ignored. Please note that this consideration of mine is specific for a 2D lidar device, which has z-axis symmetry, but it is not general. Indeed, for an RGB camera or an IMU, the reference frame orientation should be chosen carefully according to the hardware.

**Comment by pattacini** [comment] 2023-06-20 08:47
Hi @Mick3Lozzo 

Let's proceed with a right-handed CSYS with the x-axis and the y-axis oriented as required by the discussion above.

**Comment by Mick3Lozzo** [comment] 2023-06-20 09:17
<img src="https://github.com/icub-tech-iit/ergocub-software/assets/15085666/d303146d-5d94-4af8-b77e-abbf8d0048a3" width="400">

<img src="https://github.com/icub-tech-iit/ergocub-software/assets/15085666/22c56a92-86b3-4b23-8bf1-5b473db66ac0" width="400">

Added the coordinate system `CSYS_RPLIDAR_2` in the RPLIDAR commercial part, as a reference for `SCSYS_HEAD_S2_LASER` at an assembly level. Now the orientation is compliant with the standard.

@randaz81 @pattacini @mfussi66 @Nicogene

**Comment by Nicogene** [comment] 2023-06-20 09:37
If now is ok for @randaz81 and @SimoneMic we can close it.

**Closed** 2023-06-21 14:55 UTC
Labels: domain-software, prj-ergocub, report-bug, team-fix
